name: 'publish'

on:
    workflow_run:
        workflows: ['verify trusted']
        types:
            - completed

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    GH_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
    CI: true
    D2_VERBOSE: true

jobs:
    publish:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{env.GH_TOKEN}}
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - uses: actions/download-artifact@v2
              with:
                  name: app-build
            - uses: dhis2/deploy-build@master
              with:
                  # uncomment following line for monorepo apps:
                  #cwd: ./packages/app
                  build-dir: build/app
                  github-token: ${{ env.GH_TOKEN }}

    release:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        needs: [publish]
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{env.GH_TOKEN}}
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Publish release to GitHub
              run: npx @dhis2/cli-utils release
